apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xqxt7lajb-python 
  janus-idp.io/tekton: xqxt7lajb-python
  backstage.io/kubernetes-id: xqxt7lajb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xqxt7lajb-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml