apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xqxt7lajb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xqxt7lajb-python 
  name: xqxt7lajb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xqxt7lajb-python 
